POST http://127.0.0.1:8000/auth/signup/
Content-Type: application/json

{ "username": "jenny", "password": "Pass1234!", "email": "jenny@glogau.com" }

###

POST http://127.0.0.1:8000/auth/login/
Content-Type: application/json

#{ "username": "adam", "password": "Pass1234!" }
#{ "username": "kay", "password": "11111111" }
{ "username": "jenny", "password": "Pass1234!" }

###

GET http://127.0.0.1:8000/auth/test_token/
Content-Type: application/json
Authorization: token d0475957daa3b5e48629458314ce26c4f844eae
